import React from 'react'

const Policy = () => {
  return (
    <div className=' text-lg text leading-loose' >
    <div className=' text-3xl font-semibold text-center my-8'>Privacy Policy </div>


    <div className=' text-gray-600 mb-3'>Effective Date: July 1, 2020</div>
    
    <div className=' text-gray-600 mb-16'>Updated Date: May 4, 2021</div>
    
    
    
    <div className='mb-3'>Heritage Ventures (includes “us,” “we,” or “our”) is a portfolio of brands and digital platforms (such as mobile and/or TV applications) that connect people with information to help make some of life’s most important decisions. Some examples of Heritage Ventures’ brands are Allconnect, Bankrate, CNET, MyMove, Online MBA, and The Points Guy. For the purposes of this Privacy Policy, the websites, apps, and products provided by Red Ventures will be referred to as the “Services.” Certain Red Ventures Services have different privacy policies (such as our Healthline Media Sites and Services in Brazil), you should check each Service for its specific policy before use.</div>
    
    <div className='mb-3'>This Privacy Policy describes the type of personal information that we may collect for our own purposes; how we use, protect, and share that information; and the choices that you have. By using the Services, you acknowledge the information collection practices and purposes outlined in this Privacy Policy. Any capitalized terms used, but not defined, in this Privacy Policy have the meanings provided in the Terms of Use of the applicable Services.</div>
    
    <div className='mb-3' >In some circumstances, a Heritage Ventures company may receive or process Personal Information on behalf of a client. In those situations, the privacy policy of the client will apply. </div>
    

    
    
    <div className=' font-semibold text-2xl underline'>Types of Information We Collect</div>
    <div className='mb-16 mt-2'>The following are examples of the types of information that we may collect directly from you, about you, and/or from other sources, including third parties, business partners, our affiliates, or publicly available sources. </div>
    
     
    
    <div className='mb-5 underline text-xl'>Information collected directly from you: </div>
    
    <div className='mb-3'><span className=' font-semibold'>Account Registration.</span> Your name, email, phone number and other relevant information when you create an account. We also may collect information relating to the actions that you perform while logged into your account. The purpose for collection and use of this data is that we have a business need to provide account related functionalities to our users. Accounts can be used for easy checkout, save your preferences, select areas of interest, and transaction history.</div> 
    <div className='mb-3'><span className=' font-semibold'>Lead Forms and Order Placement.</span> We collect information when you use our lead and order forms on our Services. This may include your name, email, phone number, billing address, shipping address, and payment information (e.g., credit card number). In addition, these forms may ask for information specific to your request, such as car make and model for auto insurance, military service for secondary education, or other information requested by one of our business clients. The purpose of collection and use of this data is that we use your information to perform activities associated with a contract to provide you with products or services. </div>
    <div className='mb-3'><span className=' font-semibold'>Financial information.</span> On certain Red Venture Services you may provide us with information such as national identifier, credit history, income, loan amounts, and account balances related to requesting financial products and services. Examples include credit card inquiries, and loan inquiries for products such as mortgages, personal loans, and student loans. In some situations for certain Services, our GLBA notice may also apply to the collection of this information. The purpose of the collection is we have a business need to use this information to facilitate your request and connect you to lenders that deliver the products and services you request.</div>   
    <div className='mb-3'><span className=' font-semibold'> You Post on the Services.</span>Information When available on the Services, we may collect Personal Information from you when you provide or post information to our Services, including your username, comments, likes, interests, status, pictures, and references to your online presence. We may use this information for our purposes and/or make this information available to others as you request.</div>
    <div className='mb-3'><span className=' font-semibold'>Information You Provide About Others.</span> Sometimes, you may provide information about others- for example, to refer a friend for a newsletter.  We may use this information to make our Services available to the people you refer.</div> 
    <div className='mb-3'><span className=' font-semibold'>Surveys.</span> When you participate in a survey, we collect information that you provide through the survey. If the survey is provided by a third-party service provider, the third party’s privacy policy also applies to the collection, use, and disclosure of your information. The purposes of collection and use of this data are that we have a business need to understand your opinions and collect information relevant to our organization.</div> 
    <div className='mb-3'><span className=' font-semibold'>Sweepstakes or contests.</span> When you choose to participate in a sweepstakes or contest, we collect information about you, which includes contact information to notify you if you are selected. The purpose of collection and use of this data is that we have a business need to operate the contest or sweepstakes. In some contexts, we are also required by law to collect information about those that enter our sweepstakes, and we have a business interest in complying with those laws. </div>
    <div className='mb-3'><span className=' font-semibold'>Mailing List.</span> If you sign up for one of our mailing lists we collect your email address and/or postal address. The purpose of collection and use of this data is that we have a business need to share information about our products or services.</div> 
    <div className='mb-3'><span className=' font-semibold'>Partner Promotion.</span> We collect information that you may choose to provide as part of a promotion with another company. The purpose of collection and use of this data is that we have a business need to fulfill our promotions. </div>
    <div className='mb-3'><span className=' font-semibold'>Feedback/Support. </span>If you provide us feedback or contact us for support, we may collect your name and e-mail address, as well as any other content that you send to us, to reply. The purpose for collection and use of this data is that we have a business need to receive and act upon your feedback or issues.</div>
    <div className='mb-3'><span className=' font-semibold'>Employment-related data (directly from you):</span> When you choose to apply for employment with a Red Ventures Company, we collect information necessary to process your application or to retain you as an employee. This may include, among other things, your resume or CV, Social Security Number, and other information you provide during the application and recruitment process. The purpose of collection is to help us match you to open positions, facilitate the recruiting process, and perform our contract of employment or the anticipation of employment with you.</div>
    
    
    <div className=' text-xl underline mt-5 mb-6'>Information collected Automatically:  </div>
    
     <div className='mb-3'><span className=' font-semibold'>E-mail Interconnectivity.</span> If you receive email from us, we may use tools to capture data related to when you open our message, click on any links or banners it contains and make purchases. The purpose for collection and use of this data is that we have a business need to understand how you interact with our communications to you.</div> 
     <div className='mb-3'><span className=' font-semibold'>Mobile Devices (such as Phones, Tablets, Connected TVs, Gaming Consoles, and Other Digital Media Streaming Devices).</span> We may collect information from your Mobile Device, such as unique identifying information broadcast from your device when visiting one of our Services. The purposes of collection and use of this data are that we have a business need to identify unique visitors and understand how users interact with us on their devices.</div>
     <div className='mb-3'><span className=' font-semibold'>Website interactions.</span> We use technology to discover how you interact with our website (e.g., session replay). This may include which links you click on, or information that you type into our online forms. This may also include information about your device or browser. The purposes of collection and use of this data are that we have a business need to understand how you interact with our website to better improve it, and to understand your preferences and interests in order to select offerings that you might find most useful. We also have a business need to secure our Services and detect and prevent fraud.</div> 
     <div className='mb-3'><span className=' font-semibold'>Location Data.</span> When you use certain of our Services, we may solicit your permission to collect your location data.. Some features within our Services (such as location-based offers) may only function upon confirmation of your location, and therefore such features will not be available if you choose not to provide your location data. The specificity of the location data may depend on several factors, including the device you are using and how your connected to the Internet. If you enable location services for our Services, we may collect location data periodically as you use or leave open our Services. Depending on the platform you use to access our Applications (e.g., Apple's iOS, Google's Android) you may be able to control whether location data is collected from with the controls on your device.</div>
     <div className='mb-3'><span className=' font-semibold'>Cookies, generally.</span> We and our service providers operating on our behalf, and other businesses who collect information on our pages may automatically collect or receive certain information associated with you and/or your device(s) as part of your use of the  Services through device-based tracking technologies such as cookies, pixels, tags, beacons, scripts or other technology. The purposes for collection and use of this data is that we have a business need to make our website operate efficiently, provide you with different website experiences, and to provide you with ability to save your preferences such as login and preferred language. See our Cookie Policy for more information. </div>
     <div className='mb-3'><span className=' font-semibold'>Cookies, for advertising.</span> Some of our Services  participate in behavior-based advertising, which means that technology (e.g., a cookie) is used to collect information about your use of our Services to provide advertising about products and services tailored to your interests on our Services , or on other websites.  The purposes for collection and use of this data are that we have a business need to engage in behavior-based advertising and capture analytics on our Services. The information we collect may include geolocation data, such as (a) information that identifies the precise location of your mobile device (when you agree to allow an app or Service to collect this) and (b) your IP address, which may be used to estimate your approximate location. We use this information to ensure that the Services work properly, and to deliver customized content and advertising, including personalized ads, to you. See our Cookie Policy for more information. </div>
     <div className='mb-3'><span className=' font-semibold'>Cross-Device Tracking.</span> We and our service providers may collect and store information about users’ interactions with unaffiliated websites and applications that use our technologies, including cookies and similar tracking technologies. This allows us to infer the presence of a common user or household behind multiple devices or browsers, for instance, and then link those browsers and devices into a device graph. The purposes for collection and use of this data are that we have a business need to understand our users’ use of our sites across devices in order to allow users to use our services on one device and pick up seamlessly where they left off on another device. We also have a business need to provide personalized advertising on each device that is inferred from the browsing patterns on all of the devices. </div>
     <div className='mb-3'><span className=' font-semibold'>Data Analytics.</span> We use certain web analytics services, including third-party services such as Google Analytics, to help us understand and analyze how visitors use our Services. We may collect information, including your browser type, operating system, Internet Protocol (IP) address, domain name, click-activity, referring website, and/or a date/time stamp for visitors. The purpose for collection and use of this data is that we have a business need to monitor our networks and the visitors to our websites. We may receive reports based on the use of these technologies on both an individual and aggregated basis. These analytics services, including third-party services such as Google Analytics, also use this information to place advertisements for our products on other websites that you visit after your use of the Site. These advertisements may be based on actions such as the pages you visited and actions you take during your use of the Site. For further information about how Google may use data it collects through the Site you may click here. You also may choose to install the Google Analytics Opt-Out Browser Add-on to opt out of Google Analytics data collection. </div>
    
    
    <div className='mt-5 mb-6 text-xl underline'>Information we may collect from other sources: </div>
    
    <div className='mb-3'><span className=' font-semibold'>Client Information.</span> We may collect contact information such as name, e-mail, address and/or phone number of our business clients and their employees with whom we may interact. The purposes for collection and use of this data is that we have a business need to make our website operate efficiently and to provide our business clients with ability to save preferences such as login and preferred language. </div>
    <div className='mb-3'><span className=' font-semibold'>Financial information.</span> We may collect information from credit reporting services and, with your permission, financial data aggregator(s) and your financial service provider(s) when you use certain of our Services. We use the information as needed in the course of providing services you request, ongoing customer relationships, to service an account, and as permitted by state and federal law.</div>
    <div className='mb-3'><span className=' font-semibold'>Demographic Information.</span> Personal Information such as your age, gender, family size, and/or educational level. The purpose for collection and use of this data is that we have a business need to customize content, advertising and learn about our audiences. </div>
    <div className='mb-3'><span className=' font-semibold'>Activity and usage information.</span> including information about your interests, purchase behavior, and other navigation data, such as websites visited and advertisements viewed or clicked on, used to customize content and advertising. </div>
    <div className='mb-3'><span className=' font-semibold'>Publicly-observed data. </span>Such as activities on blogs, videos, and other online postings used to customize content and advertising. </div>
    <div className='mb-3'><span className=' font-semibold'>Social Media Platforms and Other Third-Party Services.</span> Some of our Services may include features that are designed to interact with social media platforms and other third-party services (e.g., Facebook, Twitter, Instagram). If you access the Services using one of these social media platforms or other third-party services, we may receive information about you from those third-parties such as account and profile data. For more information, please refer to the “Social Features" section below.</div>
    <div className='mb-12'>We may also collect information about you through interactive applications (e.g., mobile devices, third party social networking services, and embedded audio and video players), from co-branded partners and websites (e.g., on our Facebook pages), from our advertisers, and from commercially available sources (e.g., data aggregators and public databases). This Privacy Policy does not cover the practices of third parties, including those that may disclose information to us</div>
    
    <div className='mt-3 mb-12'><span className='font-semibold'>Employment-related data</span> When you choose to apply for employment with a Red Ventures Company, including information from a recruitment agency. The purpose of collection is to help us match you to open positions and facilitate the recruiting process. </div>
    
    
    <div className='mb-3 font-semibold underline'>Use and Processing of Information</div>
    
    <div className=' mb-3'>In addition to the purposes and uses described elsewhere in this policy, we may use information in the following ways:</div>
    
    <li className='mb-2'>To identify you when you engage with us and our Services.</li>
    <li className='mb-2'>To provide content recommendations based on your interactions and interests.</li>
    <li className='mb-2' >To make our Services available to you and to complete orders placed in our Services and with our Clients.</li>
    <li className='mb-2'>To process transactions associated with your use of Services for which there is a charge, including to process payments and verify your identity or payment information for your security and protection.</li>
    <li className='mb-2'>To communicate with you (e.g., about your account or updates to our terms) and to respond to inquiries related to support, employment opportunities, or other requests.</li>
    <li className='mb-2'>To deliver marketing and promotional materials related to our Services in accordance with applicable laws, including information relating to our products, services, sales, marketing research or promotions.</li>
    <li className='mb-2'>To provide you with personalized advertising on our Services based on your online activity. We use the information we have to improve our advertising systems so we can show you relevant interest-based advertising, measure the effectiveness and reach of advertisements and services, verify delivery and track performance of an advertising campaign, and ensure that an ad is only delivered when a real person is visiting the site and that the same users don’t see the same ads too frequently. You may update your preferences regarding personalized advertising by visiting the Cookie Settings link in the footer of each site to manage your settings.</li>
    <li className='mb-2'>To verify your entry into and eligibility to participate in contests, giveaways, or sweepstakes and inform you if you’ve won. If your entry information will be used for any other purposes, we will disclose that in the applicable rules governing that contest, giveaway, or sweepstakes.</li>
    <li className='mb-2'>To monitor, improve, and conduct analytics on our Services and advertiser product offerings.</li>
    <li className='mb-2'>For internal administrative purposes, such as safety and security of our Services, and to manage our relationships.</li>
    <li className='mb-2'>To permit you to participate in social sharing, including live social media feeds and to implement Social Features you choose to use.</li>
    <li className='mb-2'>The Apps in our Services may request to send you push notifications from time to time in order to update you about any events or promotions that we may be running. The Apps may also ask for your permission to access your camera and your photos. If you no longer wish to receive these types of communications, or if you've initially agreed for the application to access your camera and photos and you would like to stop the Apps from accessing them, you may turn them off at the device level. To ensure you receive proper notifications, we will need to collect certain information about your device such as operating system and user identification information.</li>
    <li className='mb-2'>To detect security incidents, and protect against malicious, deceptive, fraudulent, or illegal activity, including attempts to manipulate or violate our policies, procedures, and terms and conditions.</li>
    <li className='mb-2'>To comply with legal obligations, to establish or exercise our rights, to defend against a legal claim, and to investigate, prevent, or take action regarding possible misconduct.</li>
    <li className='mb-2'>For such other purposes not described in this Privacy Policy as you may consent (from time to time) and as otherwise permitted by law.</li>
    
    
    <div className='mt-10 mb-14'>Although the sections above describe our primary purpose(s) in collecting your information, in many situations we have more than one purpose. For example, if you complete an online purchase we may collect your information to perform our contract with you, but we also collect your information as we have a business need in maintaining your information after your transaction is complete so that we can quickly and easily respond to any questions about your order. As a result, our collection and processing of your information is based in different contexts upon your consent, our need to perform a contract, our obligations under law, and/or our need to conduct our business.</div>
    
    
    
    <div className=' font-semibold underline'>Sharing of Information</div>
    
    <div className='mt-2 mb-5'>In addition to the specific situations discussed elsewhere in this policy, we may disclose your Personal Information in the following situations:</div>
    
    <div className='mb-3'><span className=' font-semibold'>Affiliates and Acquisitions. </span>We may share your Personal Information with our corporate affiliates (e.g., parent company, sister companies, subsidiaries, joint ventures, or other companies under common control). If another company acquires, or plans to acquire, our company, business, or our assets, we will also share your Personal Information with that company using appropriate safeguards, including at the negotiation stage. </div>
    <div className='mb-3'><span className=' font-semibold'>Our Business Clients. </span>When we collect information on behalf of our business clients, we share that information with those clients.</div> 
    <div className='mb-3'><span className=' font-semibold'>Service Providers.</span> We share your information with service providers. Among other things, service providers may help us to administer our website, conduct surveys, provide technical support, assist or support our business operations and other administrative functions, process payments, and assist in the fulfillment of orders.</div> 
    <div className='mb-3'><span className=' font-semibold'>Partner Promotion.</span> We may offer contests, sweepstakes, or other promotions with third party partners. If you decide to enter a contest, sweepstakes, or promotion that is sponsored by and/or associated with a third party partner, then the information that you provide will be shared with us and with them. Their use of your information is not governed by this privacy policy.</div>
    <div className='mb-3'><span className=' font-semibold'>Audience Measurement Services.</span> We may share your Personal Information with audience measurement companies like Comscore and Nielsen that help us and other websites measure and understand the audiences that view our content.</div>
    <div className='mb-3'><span className=' font-semibold'>Video Viewing Behavior. </span>Consistent with applicable law, we may share your video viewing behavior with third parties including advertising companies, analytics partners, and social media sites.</div>
    <div className='mb-3'><span className=' font-semibold'>Aggregated and Anonymous Information.</span> We may share aggregated, anonymous information with any third party. This information is not linked to personal information that can identify you or another individual person.</div>
    <div className='mb-3'><span className=' font-semibold'>Advertising.</span> We may share certain data with Advertising platforms, including Google and Social Networks such as Twitter, Facebook, LinkedIn and Snapchat to allow us to target existing users and customers with highly relevant advertising campaigns. For the purposes of such campaigns. We may share a unique code (such as a hashed email address) with the applicable Advertising platform in order for that identifier to be matched against existing users of the relevant Advertising Platform and to identify potentially relevant audiences for targeted advertising. We use services such as Google Ads’ Customer Match, LinkedIn Matched Audiences, and Facebook Custom Audiences for these purposes.</div>
    <div className='mb-10 mt-3'>In addition to advertisements for our own goods and services, we may also facilitate third parties to advertise their own goods and services including by targeting those advertisements to those that might be most interested in them. These advertisements may be shown within our Services. In order to provide advertisements relevant to you, your IP address may be used, as well as your operating system and device type. Information about your particular device will be used to show you advertisements which work properly on that device</div>
    
    <div className='mb-3'> <span  className=' font-semibold'>Public. </span>Some of our Services may provide the opportunity to post comments, or reviews, in a public forum. If you decide to submit information on our Services, that information may be publicly available</div>
    <div className='mb-3'> <span  className=' font-semibold'>Other Persons or Entities with Your Consent. </span>With appropriate consent when required, certain Services may share your Personal Information with third party marketing partners, and they may contact you by email, telephone, postal mail or other common communication methods with marketing and promotional messages about their products or services. Sometimes we will give you the option to receive further communications from one of our advertising partners, for example when we run a competition with that advertiser. When you provide consent to receive communications from that third party advertiser, your personal information will be managed by that third party’s own privacy policy. In some cases we may also ask if you would like us to share your information with other third-parties that are not described elsewhere in this Privacy Policy.</div>
    <div className='mb-3'><span  className=' font-semibold'>Other Disclosures without Your Consent.</span> We may disclose information in response to subpoenas, warrants, or court orders, or in connection with any legal process, or to comply with relevant laws. We may also share your information to establish or exercise our rights, to defend against a legal claim, to investigate, prevent, or take action regarding possible illegal activities, suspected fraud, safety of person or property, or a violation of our policies.</div>
    
    
    <div className=' font-semibold mt-14 mb-5'>Social Features</div>
    
    <div className='mb-5'>Some of our Services may include features that are designed to permit interactions that you initiate between our site and third-party websites or services, including third-party social networks (collectively, "Social Features"). For example, you may be able to "like" or "share" content from our Services  on other websites or services, such as Facebook/Instagram, Twitter, YouTube/Google, and LinkedIn. By choosing to like or share information from our Services through these services, you should review the privacy policy of that service.</div>
    
    <div className='mb-5 font-semibold'>If you use Social Features on our Services or access our Services from Social Features, both Red Ventures and the social media services that operate those Social Features may have access to certain information about you and your use of both our site and theirs. If you are a member of a social media site and logged in, the interfaces configured on our Services may allow the social media site to connect your site visit and browsing behavior to the personal data held on your social media site. We may use this information on an aggregate basis to place ads that are based on your interests on these social media sites. These practices are governed by the privacy statements of these social networking sites and you are advised to review these separately.</div>
    
     <div className='mb-5 font-semibold'>In addition, we may request your permission to a) access and collect information available from your social networking account; and b) post information to your friends on your behalf. When you connect your social networking service with your Red Ventures account, you authorize us to access certain information about you from your social networking service to provide content and services, including to help us tailor our communications to you and to develop rich online content and services across the Services. The information we may access from your social networking services is governed by the privacy policies and settings of those third-party services.</div>
    
    <div className=' font-semibold mb-5'>The information collected and stored by the social media sites remains subject to those sites’ privacy practices, including whether they continue to share information with us, the types of information shared, and your choices with regard to what is visible to others on those third-party websites or services.</div>
    
    
    
    <div className='mt-10 mb-4 font-semibold underline'>TV and Audio Control Services</div>
    
    <div className='mt-5 mb-12'>We have partnered with certain third-party companies that offer TV and audio control services to enhance your video content viewing experience. For example, you can use third-party apps and audio control services, such as the Apple TV App or Siri, to search, recommend or access video content on the Services. These apps and audio control services may be able to collect and store information about you, including about your video viewing activities on the Services. By using your Services account with a third-party TV app or audio control service, you consent to share information about you, including the video content that you have watched on the Services. You can limit how third-party TV app or audio control services collect and store information about your video content viewing by visiting the third-party app’s privacy settings. For example, the Apple TV App allows you to discontinue the collection and storage of your video content viewing information by visiting the Apple TV App Settings page choosing the “Remove and Clear Play History” option. Click here to learn more about the Apple TV and audio control services privacy policy.</div>
    
    
    
    <div className='mt-7 mb-3 font-semibold underline'>Manage Your Information</div>
    
    <div className='mb-3'>You can make the following choices using our online form here regarding your Personal Information:</div>
    
    <div className='mb-3'><span className=' font-semibold'>Access to Your Personal Information.</span> You may request access to your Personal Information that we collect on our own behalf. If required by law, upon request, we will grant you reasonable access to the personal information that we have about you.</div>
    <div className='mb-3'><span className=' font-semibold'>Changes to Your Personal Information. </span>We rely on you to update and correct your Personal Information. Note that we may keep historical information in our backup files as permitted by law. If our Services do not permit you to update or correct certain information, contact us at the address described below. If we are processing your Personal Information on behalf of one of our clients, we will respond that we are operating as a Service Provider and are unable to act on your request.</div> 
    <div className='mb-3'><span className=' font-semibold'>Deletion of Your Personal Information.</span> When we collect information on our own behalf, we typically retain your Personal Information for the period necessary to fulfill the purposes outlined in this policy, unless a longer retention period is required or permitted by law. You may, however, request information about how long we keep a specific type of information, or request that we delete your Personal Information by contacting us at the address described below. If required by law we will grant a request to delete information, but you should note that in some situations we must keep your Personal Information to comply with our legal obligations, resolve disputes, enforce our agreements, or for another one of our business purposes. If we are processing your Personal Information on behalf of one of our clients we will respond that we are operating as a Service Provider and are unable to act on your request.</div>
    <div className='mb-3'><span className=' font-semibold'>Objection to Certain Processing.</span> When we process information on our own behalf, you may object to our use of your Personal Information by contacting us at the address described below. For example, California residents may be entitled to object, or opt-out, of having their Personal Information sold to third parties. If you are a California resident and would like to opt-out of having your information sold, please visit the following link: Do Not Sell My Personal Information. We do not discriminate against California consumers who exercise any of their rights described in this policy.  </div>
    <div className='mb-3'><span className=' font-semibold'>Revocation of Consent.</span> If you revoke your consent for the processing of personal information, then we may no longer be able to provide you services. In some cases, we may limit or deny your request to revoke consent if the law permits or requires us to do so, or if we are unable to adequately verify your identity. You may revoke consent to processing (where such processing is based upon consent) by contacting us at the address described below. </div>
    <div className='mb-6'>Note that, as required by law, in order to process your request, we will require you to prove your identity. Depending on your request, we will require, at minimum, you to provide your name, phone number, and email address. We may require additional information to verify your identity dependent upon the sensitivity of the personal information related to your request.</div>
    
    <div className='mb-6'>If you do not want to make requests for access, deletion, or Do-Not-Sell using our online form, you may call 877-366-3737. To get in touch with us about any other privacy requests, you may contact us at privacy@redventures.com or in writing at:</div>
    
    <div className=' font-semibold mb-2'>Hertage, LLC</div>
    
    <div className=' font-semibold mb-2'>1101 Red Ventures Drive</div>
    
    <div className=' font-semibold mb-2'>Fort Mill, SC 22307</div>
    
    <div className=' font-semibold mb-2'>Attn: Privacy Officer</div>
    
    <div className='mb-12'>An authorized agent may make any of the requests above by using our online form or contacting us as noted above.</div>
    
    
    
    <div className='underline'>You can also make the following choices regarding communications preferences:</div>
    
    <div className='mb-3'><span className=' font-semibold'>Promotional Emails.</span> You may choose to provide us with your email address for the purpose of allowing us to deliver newsletters, surveys, offers, and other promotional materials to you, as well as targeted offers from third parties. You can stop receiving promotional emails by following the unsubscribe instructions in emails that you receive. If you decide not to receive promotional emails, we may still send you service related communications.</div>
    <div className='mb-3'><span className=' font-semibold'>Promotional Mailings.</span> If at any time you do not want to receive offers and/or circulars from us you can remove yourself from our mailing lists by emailing us (our contact information is below) with "NO SNAIL MAIL" in the subject line along with your name, address and zip code. Please note that our mailings are prepared in advance of their being sent. Although we will remove your name from our mailing list after receiving your request, you may still receive mailings from us that had been initiated prior to your name being removed.</div>
    <div className='mb-3'><span className=' font-semibold'>Text Messages and Push Notifications.</span> If you receive a text message from us that contains promotional information you can opt-out of receiving future text messages by replying “STOP” or “UNSUBSCRIBE.” You control on your device whether you receive push notifications.</div>
    <div className='mb-3'><span className=' font-semibold'>Online Tracking.</span> We do not currently recognize automated browser signals regarding tracking mechanisms, which may include "Do Not Track" instructions.</div>
    
    
    
    
    
    <div className='mt-16 underline font-semibold mb-5'>How We Protect Personal Information</div>
    
    <div className='mb-4'>No method of transmission over the Internet, or method of electronic storage, is fully secure. While we use reasonable efforts to protect your Personal Information from unauthorized access, use, or disclosure, we cannot guarantee the security of your Personal Information. If we are required by law to inform you of a breach to your Personal Information, we may notify you electronically, in writing, or by telephone, if permitted to do so by law.</div>
    
    <div className='mb-10'>Some of our websites permit you to create an account. When you do you will be prompted to create a password. You are responsible for maintaining the confidentiality of your password, and you are responsible for any access to or use of your account by someone else that has obtained your password or device, whether or not such access or use has been authorized by you. You should notify us of any unauthorized use of your password or account.</div>
    
    
    
    <div className='mb-3 font-semibold underline'>Miscellaneous</div>
    
    <div className='mb-3'>The following additional information relates to our privacy practices:</div>
    
    <div className='mb-3'><span className=' font-semibold'>Transmission of Information to Other Countries. </span>As a multi-national company, we may transmit information between and among our affiliates. As a result, your information may be stored and processed in any country where we have facilities or in which we engage service providers. We take steps to treat personal information using the laws of the country in which we first received your information.</div>
    <div className='mb-5'>For certain jurisdictions your Personal Information may be subject to the laws of the country to which it is transferred, and if permitted by law, may be accessible without notice to you by the courts, law enforcement and national security authorities of that country. By using and participating in any of our Services or providing us with your information, you acknowledge the collection, international transfer, storage, and processing of your information.</div>
    
    <div className='mb-3'><span className=' font-semibold'>Third Party Applications/Websites.</span> We do not control the privacy practices of websites or applications that we do not own. Users are encouraged to read the privacy policy of those properties to make an informed decision regarding use of them.</div>
    <div className='mb-3'><span className=' font-semibold'>Changes to This Privacy Policy.</span> We may change our privacy policy and practices over time. We will post a notice to our website to inform you of any material changes to our privacy policy and indicate when it was most recently updated. Generally, material policy changes will apply only to information collected after the date of the change. Our privacy policy includes an “effective” and “last updated” date. The effective date refers to the date that the current version took effect. The last updated date refers to the date that the current version was last substantively modified.</div>
    <div className='mb-3'><span className=' font-semibold'>Collection of Information from Children.</span> We recognize the importance of protecting the privacy and safety of children, and our website and services are directed towards a general audience and are not directed towards children. We do not knowingly collect information about children under the age of 13 or minors otherwise defined in local law or regulation without verifiable parental consent. If we learn that someone under 13 has provided personal information through one of our websites, we will use reasonable efforts to remove that information from our databases.</div>
    <div className='mb-3'><span className=' font-semibold'>Information for California Residents.</span> California Civil Code 1798.115(c), 1798.130(a)(5)(c), 1798.130(c), and 1798.140 indicate that organizations should disclose whether certain categories of information are “sold” or transferred for an organization’s “business purpose” as those terms are defined under California law. You can find a list of the categories of information that we collect on our own behalf and how we share that information here. Please note that because this list is comprehensive it may refer to types of information that we share about people other than yourself. If you would like more information concerning the categories of personal information (if any) we share with third parties or affiliates for those parties to use for direct marketing, please submit a written request to us using the information in the "Contact Information" section</div></div>
  )
}

export default Policy